name: Integration

on:
  push:
    branches: [ main ]

jobs: 
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - run: npm install
    - run: npm run build
    #- run: rm -R /home/roed/beta.api.jamesbutler.dk/dist
    #- run: mv dist /home/roed/beta.api.jamesbutler.dk/
    - run: pm2 stop 0
    - run: pm2 start 0
    - run: pm2 save
    #- run: sudo service nginx restart
    #- run: pwd